package com.kun.androidproject.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kun.demo.DemoLoginModel;

import com.kun.androidproject.dao.DemoLoginModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig demoLoginModelDaoConfig;

    private final DemoLoginModelDao demoLoginModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        demoLoginModelDaoConfig = daoConfigMap.get(DemoLoginModelDao.class).clone();
        demoLoginModelDaoConfig.initIdentityScope(type);

        demoLoginModelDao = new DemoLoginModelDao(demoLoginModelDaoConfig, this);

        registerDao(DemoLoginModel.class, demoLoginModelDao);
    }
    
    public void clear() {
        demoLoginModelDaoConfig.clearIdentityScope();
    }

    public DemoLoginModelDao getDemoLoginModelDao() {
        return demoLoginModelDao;
    }

}
